// # Even Fibonacci numbers
// - [URL](https://projecteuler.net/problem=2)
// ## Problem 2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// > 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
//
// フィボナッチ数列の新しい項はその前の二項の和として得られる。
// フィボナッチ数列の値が 400 万を超える前の偶数の値を取る項の和を調べよ。
let rec solve: int64 -> int64 -> int64 -> int64 -> int64 =
    fun prev now sum limit ->
        let a = prev + now
        if a > limit then sum
        else if a % 2L = 0L then solve now a (sum + a) limit
        else solve now a sum limit

let fourMillion = 4000000L
solve 0L 1L 0L fourMillion |> printfn "%A"
