[package]
name = "AlgorithmsAndDataStructureByFSharp"
version = "0.1.0"
authors = ["phasetr"]
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "phasetr_sample"
path = "phasetr.rs"

[dependencies]
proconio = "0.4.3"
