hello:
	@g++ hello.cpp -o hello.out ; ./hello.out
	@rm hello.out
040:
	@g++ -std=gnu++1y -g -O0 -I/opt/boost/gcc/include -L/opt/boost/gcc/lib -o 040_00.out 040_00.cpp
	@echo ""
	@echo "SAMPLE 0"
	@echo "ANSWER: 89 71 71"
	@echo "RESULT"
	@./040_00.out < 040.txt
	@echo ""
	@rm 040_00.out
046:
	@g++ -std=gnu++1y -g -O0 -I/opt/boost/gcc/include -L/opt/boost/gcc/lib -o a.out 046_00.cpp
	@echo ""
	@echo "SAMPLE 1"
	@echo "ANSWER: 3"
	@echo "RESULT"
	@./a.out < 046_00.txt
	@echo ""
	@echo "SAMPLE 2"
	@echo "ANSWER: -1"
	@echo "RESULT"
	@./a.out < 046_01.txt
	@echo ""
	@rm a.out
055:
	@g++ -std=gnu++1y -g -O0 -I/opt/boost/gcc/include -L/opt/boost/gcc/lib -o a.out 055.cpp
	@echo ""
	@echo "SAMPLE 1"
	@echo "ANSWER:"
	@echo "5 2 4 6 1 3"
	@echo "2 5 4 6 1 3"
	@echo "2 4 5 6 1 3"
	@echo "2 4 5 6 1 3"
	@echo "1 2 4 5 6 3"
	@echo "1 2 3 4 5 6"
	@echo ""
	@echo "RESULT"
	@./a.out < 055.txt
	@echo ""
	@rm a.out
060:
	@g++ -std=gnu++1y -g -O0 -I/opt/boost/gcc/include -L/opt/boost/gcc/lib -o 060.out 060.cpp
	@echo ""
	@echo "SAMPLE 1"
	@echo "ANSWER"
	@echo "1 2 3 4 5"
	@echo "8"
	@echo ""
	@echo "RESULT"
	@./060.out < 060.txt
	@echo ""
