#r "nuget: FsUnit"
open FsUnit

(*
let S,T = "mynavi","monday"
let S,T = "tokyo","kyoto"
let S,T = "ayjspdhcophaxrxtncpmiorropjgkskilflqnvuwahyoyzaydignjejjpipzraslrjzswbdrsqndltwbrrlildhgarroxyajliulensxvqljuniivaogvwfhisywagmzyyauritdrxnhcywiwpfcpfxsdhtatmeuokgtqwuovmrfjcwbtvqjngyiknehramlocwzyeyvfnxouyhrewgqvdalkcmpxrhhgngpwfghmpzvqfldtuwusmpgbkohhbnkbcrarpssphbnvbccfzmoytcecdgzzpgdydtdxngdercnsvraxdiiefowkfyhzoptxswdyzivgplnuagweoplvuzfjyzezhvrjcdbrujxcmqudxswbolugtxzggrrbpgqrwwnvcccczvdalzgytwevldbeslozmqwfijgyjtppgbxcinfxsfyqwtzjcfqjbvcbjtsdjopfokrrljbrxihnsloixxjlwlaqdoszmrjdnsqeafgzflikpdshigcwgcnrujwoulwglwtepzupvflfdqgdjctnvcbruqrnxogcwizlqceibcthplhtmzztevhzxtogogkqsubpzmmxlxlflytbapxculktvrnmxsrrlftnijluqisipldqorggnwvlqshgyzkxynecncpeqrxedmdteupwuiforpagvnimfdffmxhuclznxositwupllmfmyxrmoyotptuafoeiwrqplkznzubnyhgspgehabdhlvtpwxuxycgzdejaxfbkeieizqfuryllssciclnjstarxzlcnmmbuuecocprxmyhwxpawuwguerbyywfwbupatkywrbsuvkrkmcpktksiynccmpvtbidamdrwwlgeejzsgtxtcxgtkiijviifrvsveeqkv","wprmjsudodjusoexdickjchfhunplrodubzkmjlunzmjgbnwbjfxdoagpaqqnvhbmovzaezfryjmfekcueehhovmijbdzcqohambcgsczaeuuvomvydifwhakvgnjubsnpgzjrbdmizufrnoftjrqykalrwszfcrznfjqfgzmclnnjnzcsxppcghklrfuptfnpecdoxklsfpfuqjwcpewugkyrdjjosecnlomlbiiamvhlxgubxtwomqqotdboeffdqagkwvqaagbgyxfupeixesnwriceaqkbhhkmfuivnlwizrczygannqnaeqeuakabvcenmbwrjxaluimmgrkmjfsmqizfwhojzsxebcjzkhljfehprgzwrxtpdndwvnqrbhenvlgqwgfunohtiuezphzbgoibvdevrezuahpolvrczwdewoevnzkmhrioyegwhizckyxhvdohkdgxjdcqcgnwqcjyzmrcqmvmktorsauzagyvppuaqnxtvbpmndnwlsnkpmmoopfclaswlfknzwskjmkuhmifiqufhektxpnxiknehdnaokzpbwctrbxxdihfykyytvkwhjfhvwypdzmxfvnnvxvaauskszuxduiecgnzzqptqoqsvysydrmzihlsnggygdtsevwboqjxqtoxkhumxomrvzpjketdatznpfiebpdtqfakegvnrpaehlnxmuysdkgqwwmwwvdjkbnrtqavhdajrhiwzwxzabanzlrqhlqkysmroykkbhgoqzssfnjmpyzdgwlgodfuortkvunhvnkfivvxxablmnblwdoougmccocbkimscazghzvwhwbitzrdjohodybqyovqajlitbitvqtpncmkvzskkkbkfwxxqrgqcfhknxfoqjlwarapbfzeljdarzrlatlxzjvsghkjmlrxosgvjpipysxvakaiejuhcgxwtodjlgqcjrvihkpnwauzcwftkmfesduhcfjsrtcqijhohitlpplfxhqszfosofzshcsguvakgsluiixbxfyicupycxfyxfazgsodendaqauhlwsusvcozrvvxuelkcdlmbmtoejxzwcjxuijpsfbaxzakoptpahcuuxwfqfxslpxbfjkjimhhqdbgaxhosjgxztetgycgbcjmudpmfxsvdaqbgvdbdixirmsyibokgwjddmmgktbprrxpdotrslhutjrxternpkxfwcbrxzadseciomtjoyqzbydqfdlzipvrmpuebnhpfqsnclnpwvutwjpbhheyspvpbfxqjcmjkuuxeosdntiscyzkenfyvcstuiftqhxcksooesorejgdeotkptsqvpiawfeflvuknojkdryuuhtoemlmlagdktucgpeekqbtqvxbysvkdgglfydygncrcshbplpfmmmqwhegcghpgfjdmoqsjqzmwplkjlvsbazauamufgyusowzxsgyjiaypfutnhethjhhrqdzrukgyiifsxsjjgbesyeuzsqnnlwppwsvugxzzoarinbitcluxbtqottzudjddybcqbctkqyktunvvfvkppimycmxfapzvbrisyqkirxeuvsshyzljuzkqghjnidlukdcfixwtilngewdnrusilbkdwcjasidyvlftxolotkjssflucoxnkiatkpvujkwmpclfytleiwtbogawqnqogltjzavihivdpvsrrmogopwaytssafkueqdjszrulnsnjhrnkfqbergglvkgrmtziqcmrqnburdkwlmxxexyjcpwgowqinrijvhgbqvuolsprjpfhuiynhhaqbtutioztgqarpjyfjeisozeankpwknnlokyscfffponpusyilbciqkyaszyomhzzvsfkeprenfwundoyvhgjlposozhjkxcntlowokasyfwyzepcmnlyvwbjfdffaetigrwyycraudcksxpcsosggdnlvhcyozvrncxdgnulpfdxfhn"
*)
let solve S T =
  let sLen = String.length S
  let tLen = String.length T
  (Array2D.create (sLen+1) (tLen+1) 0, [|0..sLen-1|])
  ||> Array.fold (fun dp i ->
    [|0..tLen-1|] |> Array.iter (fun j ->
      if S.[i]=T.[j] then dp.[i+1,j+1] <- dp.[i,j]+1
      else dp.[i+1,j+1] <- max dp.[i,j+1] dp.[i+1,j])
    dp)
  |> fun dp -> dp.[sLen,tLen]

let S = stdin.ReadLine()
let T = stdin.ReadLine()
solve S T |> stdout.WriteLine

solve "mynavi" "monday" |> should equal 3
solve "tokyo" "kyoto" |> should equal 3
// in11.txt
solve "ayjspdhcophaxrxtncpmiorropjgkskilflqnvuwahyoyzaydignjejjpipzraslrjzswbdrsqndltwbrrlildhgarroxyajliulensxvqljuniivaogvwfhisywagmzyyauritdrxnhcywiwpfcpfxsdhtatmeuokgtqwuovmrfjcwbtvqjngyiknehramlocwzyeyvfnxouyhrewgqvdalkcmpxrhhgngpwfghmpzvqfldtuwusmpgbkohhbnkbcrarpssphbnvbccfzmoytcecdgzzpgdydtdxngdercnsvraxdiiefowkfyhzoptxswdyzivgplnuagweoplvuzfjyzezhvrjcdbrujxcmqudxswbolugtxzggrrbpgqrwwnvcccczvdalzgytwevldbeslozmqwfijgyjtppgbxcinfxsfyqwtzjcfqjbvcbjtsdjopfokrrljbrxihnsloixxjlwlaqdoszmrjdnsqeafgzflikpdshigcwgcnrujwoulwglwtepzupvflfdqgdjctnvcbruqrnxogcwizlqceibcthplhtmzztevhzxtogogkqsubpzmmxlxlflytbapxculktvrnmxsrrlftnijluqisipldqorggnwvlqshgyzkxynecncpeqrxedmdteupwuiforpagvnimfdffmxhuclznxositwupllmfmyxrmoyotptuafoeiwrqplkznzubnyhgspgehabdhlvtpwxuxycgzdejaxfbkeieizqfuryllssciclnjstarxzlcnmmbuuecocprxmyhwxpawuwguerbyywfwbupatkywrbsuvkrkmcpktksiynccmpvtbidamdrwwlgeejzsgtxtcxgtkiijviifrvsveeqkv" "wprmjsudodjusoexdickjchfhunplrodubzkmjlunzmjgbnwbjfxdoagpaqqnvhbmovzaezfryjmfekcueehhovmijbdzcqohambcgsczaeuuvomvydifwhakvgnjubsnpgzjrbdmizufrnoftjrqykalrwszfcrznfjqfgzmclnnjnzcsxppcghklrfuptfnpecdoxklsfpfuqjwcpewugkyrdjjosecnlomlbiiamvhlxgubxtwomqqotdboeffdqagkwvqaagbgyxfupeixesnwriceaqkbhhkmfuivnlwizrczygannqnaeqeuakabvcenmbwrjxaluimmgrkmjfsmqizfwhojzsxebcjzkhljfehprgzwrxtpdndwvnqrbhenvlgqwgfunohtiuezphzbgoibvdevrezuahpolvrczwdewoevnzkmhrioyegwhizckyxhvdohkdgxjdcqcgnwqcjyzmrcqmvmktorsauzagyvppuaqnxtvbpmndnwlsnkpmmoopfclaswlfknzwskjmkuhmifiqufhektxpnxiknehdnaokzpbwctrbxxdihfykyytvkwhjfhvwypdzmxfvnnvxvaauskszuxduiecgnzzqptqoqsvysydrmzihlsnggygdtsevwboqjxqtoxkhumxomrvzpjketdatznpfiebpdtqfakegvnrpaehlnxmuysdkgqwwmwwvdjkbnrtqavhdajrhiwzwxzabanzlrqhlqkysmroykkbhgoqzssfnjmpyzdgwlgodfuortkvunhvnkfivvxxablmnblwdoougmccocbkimscazghzvwhwbitzrdjohodybqyovqajlitbitvqtpncmkvzskkkbkfwxxqrgqcfhknxfoqjlwarapbfzeljdarzrlatlxzjvsghkjmlrxosgvjpipysxvakaiejuhcgxwtodjlgqcjrvihkpnwauzcwftkmfesduhcfjsrtcqijhohitlpplfxhqszfosofzshcsguvakgsluiixbxfyicupycxfyxfazgsodendaqauhlwsusvcozrvvxuelkcdlmbmtoejxzwcjxuijpsfbaxzakoptpahcuuxwfqfxslpxbfjkjimhhqdbgaxhosjgxztetgycgbcjmudpmfxsvdaqbgvdbdixirmsyibokgwjddmmgktbprrxpdotrslhutjrxternpkxfwcbrxzadseciomtjoyqzbydqfdlzipvrmpuebnhpfqsnclnpwvutwjpbhheyspvpbfxqjcmjkuuxeosdntiscyzkenfyvcstuiftqhxcksooesorejgdeotkptsqvpiawfeflvuknojkdryuuhtoemlmlagdktucgpeekqbtqvxbysvkdgglfydygncrcshbplpfmmmqwhegcghpgfjdmoqsjqzmwplkjlvsbazauamufgyusowzxsgyjiaypfutnhethjhhrqdzrukgyiifsxsjjgbesyeuzsqnnlwppwsvugxzzoarinbitcluxbtqottzudjddybcqbctkqyktunvvfvkppimycmxfapzvbrisyqkirxeuvsshyzljuzkqghjnidlukdcfixwtilngewdnrusilbkdwcjasidyvlftxolotkjssflucoxnkiatkpvujkwmpclfytleiwtbogawqnqogltjzavihivdpvsrrmogopwaytssafkueqdjszrulnsnjhrnkfqbergglvkgrmtziqcmrqnburdkwlmxxexyjcpwgowqinrijvhgbqvuolsprjpfhuiynhhaqbtutioztgqarpjyfjeisozeankpwknnlokyscfffponpusyilbciqkyaszyomhzzvsfkeprenfwundoyvhgjlposozhjkxcntlowokasyfwyzepcmnlyvwbjfdffaetigrwyycraudcksxpcsosggdnlvhcyozvrncxdgnulpfdxfhn" |> should equal 416

let solveWithSubString S T =
  let sLen = String.length S
  let tLen = String.length T
  (Array2D.init (sLen+1) (tLen+1) (fun _ _ -> 0,([]:char list)), [|0..sLen-1|])
  ||> Array.fold (fun dp i ->
    [|0..tLen-1|] |> Array.iter (fun j ->
      if S.[i]=T.[j] then dp.[i+1,j+1] <- (1+fst dp.[i,j], (S.[i]::snd dp.[i,j]))
      else
        dp.[i+1,j+1] <-
          let (n1,s1),(n2,s2) = dp.[i,j+1],dp.[i+1,j]
          if n1<n2 then (n2,s2) else (n1,s1))
    dp)
  |> fun dp -> dp.[sLen,tLen]
